name: Create Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      BUMP_STRATEGY:
        description: "Bump strategy (major, minor, patch)"
        required: true

jobs:
  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:web

  build-mobile:
    name: Build Mobile App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: yarn build:mobile

  generate-release:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build mobile code
        run: yarn build:mobile

      - name: Generate APK
        run: yarn build:mobile

      - name: Resolve bump strategy
        id: bump_strategy
        env:
          BUMP_STRATEGY: ${{ github.event.inputs.BUMP_STRATEGY }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            ## Validate input
            if [[ "$BUMP_STRATEGY" != "major" && "$BUMP_STRATEGY" != "minor" && "$BUMP_STRATEGY" != "patch" ]]; then
              echo "Invalid bump strategy '$BUMP_STRATEGY'."
              exit 1
            fi
            # echo "{name}={value}" >> $GITHUB_OUTPUT
            echo "strategy=$BUMP_STRATEGY" >> $GITHUB_OUTPUT
          else
            if [[ "${{ github.event.head_commit.message }}" == *"[MAJOR]"* ]]; then
              echo "strategy=major" >> $GITHUB_OUTPUT
            elif [[ "${{ github.event.head_commit.message }}" == *"[MINOR]"* ]]; then
              echo "strategy=minor" >> $GITHUB_OUTPUT
            else
              echo "strategy=patch" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Get latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: ${{ steps.bump_strategy.outputs.strategy }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{ steps.get_latest_tag.outputs.tag }}
          toTag: ${{ steps.tag_version.outputs.new_tag }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## 🐞 BugFixes",
                  "labels": ["bugfix"]
                },
                {
                  "title": "## 🔨 Refactors",
                  "labels": ["refactor"]
                },
                {
                  "title": "## 💬 Other",
                  "labels": ["other"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename APK
        id: rename_apk
        run: |
          mv apps/mobile/android/app/build/outputs/apk/release/app-release.apk apps/mobile/android/app/build/outputs/apk/release/SportApp-${{ steps.tag_version.outputs.new_tag }}.apk
          mv apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk apps/mobile/android/app/build/outputs/apk/debug/SportApp_debug-${{ steps.tag_version.outputs.new_tag }}.apk
          echo "apk_debug=apps/mobile/android/app/build/outputs/apk/debug/SportApp_debug-${{ steps.tag_version.outputs.new_tag }}.apk" >> $GITHUB_OUTPUT
          echo "apk_release=apps/mobile/android/app/build/outputs/apk/release/SportApp-${{ steps.tag_version.outputs.new_tag }}.apk" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          artifacts: |
            ${{ steps.rename_apk.outputs.apk_debug }},${{ steps.rename_apk.outputs.apk_release }}
          artifactContentType: application/vnd.android.package-archive
